---
# Source: ui-deploy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: react-ui
    env: prod
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: react-ui
  type: NodePort
---
# Source: ui-deploy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui-dep
  labels:
    app: react-ui
    env: prod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
        env: prod
    spec:
      containers:
        - name: react-ui
          image: vikashashoke/ui
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 0.5
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 2Gi
---
# Source: ui-deploy/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    app: react-ui
    env: prod
spec:
  maxReplicas: 10
  minReplicas: 4
  scaleTargetRef: 
    apiVersion: extensions/v1
    kind: Deployment
    name: react-ui
  targetCPUUtilizationPercentage: 50
